### ISSUE TITLE
Change default hold key in Macs to command instead of control

### ISSUE THREAD

**Issue by QarthO** [tierrif/chat-utils#27]
On the latest update you introduced an optional feature to use a copy key.

If you have Mod Menu installed, you can change the key which is great. But normally mods also include any keybinds in the default vanilla keybinds. Not sure if this is bug, or just needs to be implemented. But having all the hotkeys all in one place is super helpful fo the end user.

Dont think its relevant, but here's my setup:

Using MultiMC:
- Minecraft Version 1.20.1
- Fabric Loader: 0.14.21

Mods:
- Chat Utils Mod: 1.10.0+1.20.1
- Cloth Config v11: 11.1.106
- Fabric API: 0.85.0+1.20.1
- Mod Menu: 7.1.0
Running on MacOS Ventura 13.4.1

Another side note thats moreso a QoL fix for the new hotkey. You have the default being Left Control. Mac users use the Command key instead of Control. Is there anyway you're able to have the mod check the OS, and set the default to Command instead of Left Control if the user is on Mac?

**Comment by tierrif** [comment]
This is not a bug, it's intentional. Keybinds registered under "controls" will conflict with other keybinds (e.g. if you set left ctrl as the copy keybind and have ctrl set for sprinting, you won't be able to sprint and chat-utils will take priority).

I'm afraid this is Minecraft behaviour that can't be circumvented without applying changes that could break other mods. This is the friendliest way I found to implement the keybind, which is a HUD-exclusive keybind.

If you have any suggestions though, please do make them!

About Mac users, I'd expect Minecraft to consider ctrl as cmd in Mac, but if that's not the case I can change the default keybind to something else instead of complicating things so much.

**Comment by QarthO** [comment]
Ah yes, that makes perfect sense!

Do you know if there's anyway to have the option in the keybinds be grayed out or a msg/button that says change the keybind in mod menu?

And the mac cmd/ctrl issue isn't too big, cause Minecraft by default isn't mac friendly, so we can expect to have to switch things over to command. Would just be a nice QoL change.

**Comment by tierrif** [comment]
I just looked into it though, and even though I'm unfamiliar with Macs, they do have a control key, does it not work for you in this situation?

**Comment by QarthO** [comment]
yes the control key works! This would be just a QoL change. Basically use the command key in place of control for hotkeys.
For example in windows CTRL+C is copy. However on a mac is CMD+C. Nearly all developers (not just Minecraft, any software) incorporate a CMDorCTRL key. Where when assigning keybinds on setup, will basically run a check, if os = mac use command, else use control.

Minecrat even did this. For example, when dropping a full item stack. In windows you press CTRL+Q, in mac you need to press CMD+Q. And this is natively done in Minecraft, mac users don't have to make this change.

(a fun tidbit tho, CMD+Q is macs ALT+F4... sooo clearly some oversight from mojang)

**Comment by tierrif** [comment]
In a coming version I will add this (or anyone who feels like contributing can add it too). In a nutshell what needs doing is very simple:
In the configuration value declaration for the hold key, instead of immediately setting the default value to GLFW.GLFW_KEY_LEFT_CONTROL, run an OS check and set it to GLFW.GLFW_KEY_LEFT_COMMAND if it's Mac.
